name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-dev.txt') }}
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
      - run: npm ci
      - run: npm audit --production
      - run: npm run build
      - run: npm run lint
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
      - run: npm test -- --coverage
      - run: |
          mkdir -p logs
          npx railway logs --service "$RAILWAY_SERVICE" --environment "$RAILWAY_ENV" --follow > logs/latest_railway.log &
          sleep 5
          kill $!
        env:
          RAILWAY_SERVICE: ${{ secrets.RAILWAY_SERVICE || '' }}
          RAILWAY_ENV: ${{ secrets.RAILWAY_ENV || '' }}
      - run: npx snyk test
        continue-on-error: true
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
      - uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/
      - uses: actions/upload-artifact@v4
        with:
          name: railway-logs
          path: logs/latest_railway.log
      - run: rm -rf tmp-repo-* || true
      - run: rm -rf logs || true
