name: Extract PTCGP Cards

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '0 3 * * 1'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ptcgp-data-extraction repo
        uses: actions/checkout@v4

      - name: Clone tcgdex/cards-database
        uses: actions/checkout@v4
        with:
          repository: tcgdex/cards-database
          path: tcgdex

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install
        # Hier KEIN working-directory nötig, default ist das Hauptrepo!

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Run export script
        run: npm run export
        # Hier KEIN working-directory nötig, default ist das Hauptrepo!

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Automated data extraction'
          file_pattern: 'data/cards.json data/sets.json'
        # Hier KEIN working-directory möglich!
